version: "3"
services:
  db-teste:
    image: "mongo:latest"
    container_name: db-teste
    ports:
      - "27031:27017"
    networks:
      - custom
    restart: always
    volumes:
      - /srv/docker/jenkins_home/volumes/contadigital/saldo:/data/db

  ms-teste:
    container_name: ms-teste
    build: .
    image: ms-teste
    networks:
      - custom
    depends_on:
      - db-teste
    external_links:
      - root_rabbit1_1:rabbit
    links:
      - db-teste

networks:
  custom:
    external: true